config_version: 0.4
genome_folder: /project/shefflab//deploy/test-data/genomes
genome_servers: ['http://refgenomes.databio.org']
genomes:
  58de7f33a36ccd9d6e3b1b3afe6b9f37cd5b2867bbfb929a:
    assets:
      fasta:
        asset_description: DNA sequences in the FASTA format, indexed FASTA (produced with samtools index) and chromosome sizes file
        tags:
          default:
            asset_path: fasta
            asset_digest: 59fed5ec3c3a95bc5709b24b8f2cf7bf
            seek_keys:
              fasta: 58de7f33a36ccd9d6e3b1b3afe6b9f37cd5b2867bbfb929a.fa
              fai: 58de7f33a36ccd9d6e3b1b3afe6b9f37cd5b2867bbfb929a.fa.fai
              chrom_sizes: 58de7f33a36ccd9d6e3b1b3afe6b9f37cd5b2867bbfb929a.chrom.sizes
            asset_parents: []
        default_tag: default
    aliases: ['hg38']
    genome_description: test
  ebf26d2f064462bea7029e6b4d2298967d7435bff82ed224:
    assets:
      fasta:
        asset_description: DNA sequences in the FASTA format, indexed FASTA (produced with samtools index) and chromosome sizes file
        tags:
          default:
            asset_path: fasta
            asset_digest: 4a749d4e74b057d0efa0c8398ebcb871
            seek_keys:
              fasta: ebf26d2f064462bea7029e6b4d2298967d7435bff82ed224.fa
              fai: ebf26d2f064462bea7029e6b4d2298967d7435bff82ed224.fa.fai
              chrom_sizes: ebf26d2f064462bea7029e6b4d2298967d7435bff82ed224.chrom.sizes
            asset_parents: []
        default_tag: default
    aliases: ['human_repeats']
    genome_description: test
  511fb1178275e7d529560d53b949dba40815f195623bce8e:
    assets:
      fasta:
        asset_description: DNA sequences in the FASTA format, indexed FASTA (produced with samtools index) and chromosome sizes file
        tags:
          default:
            asset_path: fasta
            asset_digest: 4eb430296bc02ed7e4006624f1d5ac53
            seek_keys:
              fasta: 511fb1178275e7d529560d53b949dba40815f195623bce8e.fa
              fai: 511fb1178275e7d529560d53b949dba40815f195623bce8e.fa.fai
              chrom_sizes: 511fb1178275e7d529560d53b949dba40815f195623bce8e.chrom.sizes
            asset_parents: []
        default_tag: default
    aliases: ['rCRSd']
    genome_description: test
  194f8681e3d9e35b9eca2d17ec5e36bbf5e8c2beea486496:
    assets:
      fasta:
        asset_description: DNA sequences in the FASTA format, indexed FASTA (produced with samtools index) and chromosome sizes file
        tags:
          default:
            asset_path: fasta
            asset_digest: 8dfe402f7d29d5b036dd8937119e4404
            seek_keys:
              fasta: 194f8681e3d9e35b9eca2d17ec5e36bbf5e8c2beea486496.fa
              fai: 194f8681e3d9e35b9eca2d17ec5e36bbf5e8c2beea486496.fa.fai
              chrom_sizes: 194f8681e3d9e35b9eca2d17ec5e36bbf5e8c2beea486496.chrom.sizes
            asset_parents: []
        default_tag: default
    aliases: ['mouse_chrM2x']
    genome_description: test
remote_url_base: https://refgenie.s3.amazonaws.com
genome_archive_folder: /project/shefflab//deploy/test-data/genomes/archive
genome_archive_config: refgenie_config_archive.yaml
