config_version: 0.4
genome_folder: /project/shefflab//deploy/rg.databio.org/genomes
genome_servers: 
 - http://refgenomes.databio.org
genomes:
  43f14ba8beed34d52edb244e26f193df6edbb467bd55d37a:
    assets:
      fasta:
        asset_description: DNA sequences in the FASTA format, indexed FASTA (produced with samtools index) and chromosome sizes file
        tags:
          default:
            asset_path: fasta
            asset_digest: 8dfe402f7d29d5b036dd8937119e4404
            seek_keys:
              fasta: 43f14ba8beed34d52edb244e26f193df6edbb467bd55d37a.fa
              fai: 43f14ba8beed34d52edb244e26f193df6edbb467bd55d37a.fa.fai
              chrom_sizes: 43f14ba8beed34d52edb244e26f193df6edbb467bd55d37a.chrom.sizes
            asset_parents: []
            asset_children: 
             - 43f14ba8beed34d52edb244e26f193df6edbb467bd55d37a/bwa_index:default
             - 43f14ba8beed34d52edb244e26f193df6edbb467bd55d37a/bowtie2_index:default
            archive_digest: 41889bb9c3ab7256bad9cda38c066063
            archive_size: 9.1KB
            asset_size: 39.3KB
            legacy_archive_digest: 12e37cecf30290cd01b0b28769108d7a
        default_tag: default
      bowtie2_index:
        asset_description: Genome index for bowtie, produced with bowtie-build
        tags:
          default:
            asset_path: bowtie2_index
            asset_digest: 738d82a0ff63864726c442b2276d06c0
            seek_keys:
              bowtie2_index: 43f14ba8beed34d52edb244e26f193df6edbb467bd55d37a
            asset_parents: 
             - 43f14ba8beed34d52edb244e26f193df6edbb467bd55d37a/fasta:default
            archive_digest: 526c82a9e5c7df14fc95a515731646fc
            archive_size: 119.3KB
            asset_size: 8.1MB
            asset_children: []
            legacy_archive_digest: f7f04eb63baae5aa192bff01c54ab824
        default_tag: default
      bwa_index:
        asset_description: Genome index for Burrows-Wheeler Alignment Tool, produced with bwa index
        tags:
          default:
            asset_path: bwa_index
            asset_digest: 914dec83dcfab73e056717d33ecfd465
            seek_keys:
              bwa_index: 43f14ba8beed34d52edb244e26f193df6edbb467bd55d37a.fa
            asset_parents: 
             - 43f14ba8beed34d52edb244e26f193df6edbb467bd55d37a/fasta:default
            archive_digest: e78c0965d241c277c42d259fe03e8ce5
            archive_size: 32.2KB
            asset_size: 61.6KB
            asset_children: []
            legacy_archive_digest: b714d7da1300f9b3fff4721a0416ad09
        default_tag: default
    aliases: 
     - mouse_chrM2x
    genome_description: test description mouse chrM2x
  94e0d21feb576e6af61cd2a798ad30682ef2428bb7eabbb4:
    assets:
      fasta:
        asset_description: DNA sequences in the FASTA format, indexed FASTA (produced with samtools index) and chromosome sizes file
        tags:
          default:
            asset_path: fasta
            asset_digest: 4eb430296bc02ed7e4006624f1d5ac53
            seek_keys:
              fasta: 94e0d21feb576e6af61cd2a798ad30682ef2428bb7eabbb4.fa
              fai: 94e0d21feb576e6af61cd2a798ad30682ef2428bb7eabbb4.fa.fai
              chrom_sizes: 94e0d21feb576e6af61cd2a798ad30682ef2428bb7eabbb4.chrom.sizes
            asset_parents: []
            asset_children: 
             - 94e0d21feb576e6af61cd2a798ad30682ef2428bb7eabbb4/bowtie2_index:default
            archive_digest: 7f9a7894b07bf1f9ba3756ecbd1b269f
            archive_size: 8.6KB
            asset_size: 39.9KB
            legacy_archive_digest: 0e887ad0af15ddcca990dbe5ca851905
        default_tag: default
      bowtie2_index:
        asset_description: Genome index for bowtie, produced with bowtie-build
        tags:
          default:
            asset_path: bowtie2_index
            asset_digest: 1262e30d4a87db9365d501de8559b3b4
            seek_keys:
              bowtie2_index: 94e0d21feb576e6af61cd2a798ad30682ef2428bb7eabbb4
            asset_parents: 
             - 94e0d21feb576e6af61cd2a798ad30682ef2428bb7eabbb4/fasta:default
            archive_digest: 545a99b234d6e966d9e140c4777a950a
            archive_size: 116.5KB
            asset_size: 8.1MB
            asset_children: []
            legacy_archive_digest: f118236047f1cdc45eab09d403bc7cf7
        default_tag: default
    aliases: 
     - rCRSd
    genome_description: test description rCRSd
  7319f9237651755047bc40d7f7a9770d42a537e840f4e105:
    assets:
      fasta:
        asset_description: DNA sequences in the FASTA format, indexed FASTA (produced with samtools index) and chromosome sizes file
        tags:
          default:
            asset_path: fasta
            asset_digest: 4a749d4e74b057d0efa0c8398ebcb871
            seek_keys:
              fasta: 7319f9237651755047bc40d7f7a9770d42a537e840f4e105.fa
              fai: 7319f9237651755047bc40d7f7a9770d42a537e840f4e105.fa.fai
              chrom_sizes: 7319f9237651755047bc40d7f7a9770d42a537e840f4e105.chrom.sizes
            asset_parents: []
            asset_children: 
             - 7319f9237651755047bc40d7f7a9770d42a537e840f4e105/hisat2_index:default
             - 7319f9237651755047bc40d7f7a9770d42a537e840f4e105/bwa_index:default
            archive_digest: 59186a199f2d399d56c74a81613dad81
            archive_size: 33.8KB
            asset_size: 154.2KB
            legacy_archive_digest: 46a2b53d44a6c0dc4c804cc128883bbb
        default_tag: default
      hisat2_index:
        asset_description: Genome index for HISAT2, produced with hisat2-build
        tags:
          default:
            asset_path: hisat2_index
            asset_digest: a2650e2937b3d5f0f50de29410067329
            seek_keys:
              hisat2_index: 7319f9237651755047bc40d7f7a9770d42a537e840f4e105
            asset_parents: 
             - 7319f9237651755047bc40d7f7a9770d42a537e840f4e105/fasta:default
            archive_digest: 5cdf4cdb38818114e5db3529d69af27c
            archive_size: 347.6KB
            asset_size: 4.6MB
            asset_children: []
            legacy_archive_digest: 1dec9091601e40f5396e98fc62519f1e
        default_tag: default
      bwa_index:
        asset_description: Genome index for Burrows-Wheeler Alignment Tool, produced with bwa index
        tags:
          default:
            asset_path: bwa_index
            asset_digest: 58073f1e9e77cb2c3b57dc3d26e22e37
            seek_keys:
              bwa_index: 7319f9237651755047bc40d7f7a9770d42a537e840f4e105.fa
            asset_parents: 
             - 7319f9237651755047bc40d7f7a9770d42a537e840f4e105/fasta:default
            archive_digest: a2f692078c879f6ede6ee1a7816207db
            archive_size: 131.0KB
            asset_size: 252.6KB
            asset_children: []
            legacy_archive_digest: ca601a47e82c5fa3e199d9ee2408826c
        default_tag: default
    aliases: 
     - human_repeats
    genome_description: test description human repeats
  2230c535660fb4774114bfa966a62f823fdb6d21acf138d4:
    assets:
      fasta:
        asset_description: DNA sequences in the FASTA format, indexed FASTA (produced with samtools index) and chromosome sizes file
        tags:
          default:
            asset_path: fasta
            asset_digest: 59fed5ec3c3a95bc5709b24b8f2cf7bf
            seek_keys:
              fasta: 2230c535660fb4774114bfa966a62f823fdb6d21acf138d4.fa
              fai: 2230c535660fb4774114bfa966a62f823fdb6d21acf138d4.fa.fai
              chrom_sizes: 2230c535660fb4774114bfa966a62f823fdb6d21acf138d4.chrom.sizes
            asset_parents: []
        default_tag: default
    aliases: 
     - hg38
    genome_description: test description hg38
remote_url_base: http://awspds.refgenie.databio.org/rg.databio.org/
genome_archive_folder: /project/shefflab//deploy/rg.databio.org/genomes/archive
genome_archive_config: refgenie_config_archive.yaml
