config_version: 0.4
genome_folder: /project/shefflab//deploy/rg.databio.org/genomes
genome_servers: 
 - http://refgenomes.databio.org
genomes:
  2230c535660fb4774114bfa966a62f823fdb6d21acf138d4:
    assets:
      fasta:
        asset_description: DNA sequences in the FASTA format, indexed FASTA (produced with samtools index) and chromosome sizes file
        tags:
          default:
            asset_path: fasta
            asset_digest: 59fed5ec3c3a95bc5709b24b8f2cf7bf
            seek_keys:
              fasta: 2230c535660fb4774114bfa966a62f823fdb6d21acf138d4.fa
              fai: 2230c535660fb4774114bfa966a62f823fdb6d21acf138d4.fa.fai
              chrom_sizes: 2230c535660fb4774114bfa966a62f823fdb6d21acf138d4.chrom.sizes
            asset_parents: []
            asset_children: 
             - 2230c535660fb4774114bfa966a62f823fdb6d21acf138d4/bowtie2_index:default
            archive_digest: 7f28d08efddaa02de25f0dba53ffba56
            archive_size: 833.4MB
            asset_size: 2.9GB
            legacy_archive_digest: 1034d2f7a27d00dbbad2a8427a1f9a82
        default_tag: default
      bowtie2_index:
        asset_description: Genome index for bowtie, produced with bowtie-build
        tags:
          default:
            asset_path: bowtie2_index
            asset_digest: 04880a3192a69bbfdc36da25b67203cb
            seek_keys:
              bowtie2_index: 2230c535660fb4774114bfa966a62f823fdb6d21acf138d4
            asset_parents: 
             - 2230c535660fb4774114bfa966a62f823fdb6d21acf138d4/fasta:default
            archive_digest: ccd61af740f0e654c320ec80a868b4a0
            archive_size: 3.5GB
            asset_size: 3.9GB
            asset_children: []
            legacy_archive_digest: 7d255692096d82b8c3a3d2950a1a9d16
        default_tag: default
    aliases: 
     - hg38
    genome_description: test description hg38
  7319f9237651755047bc40d7f7a9770d42a537e840f4e105:
    assets:
      fasta:
        asset_description: DNA sequences in the FASTA format, indexed FASTA (produced with samtools index) and chromosome sizes file
        tags:
          default:
            asset_path: fasta
            asset_digest: 4a749d4e74b057d0efa0c8398ebcb871
            seek_keys:
              fasta: 7319f9237651755047bc40d7f7a9770d42a537e840f4e105.fa
              fai: 7319f9237651755047bc40d7f7a9770d42a537e840f4e105.fa.fai
              chrom_sizes: 7319f9237651755047bc40d7f7a9770d42a537e840f4e105.chrom.sizes
            asset_parents: []
            asset_children: 
             - 7319f9237651755047bc40d7f7a9770d42a537e840f4e105/hisat2_index:default
             - 7319f9237651755047bc40d7f7a9770d42a537e840f4e105/bwa_index:default
            archive_digest: 7f806088a7180cc05ef534ce5522b2a1
            archive_size: 33.8KB
            asset_size: 154.9KB
            legacy_archive_digest: a41fc195f2edd7325fd7b828e941a92f
        default_tag: default
      hisat2_index:
        asset_description: Genome index for HISAT2, produced with hisat2-build
        tags:
          default:
            asset_path: hisat2_index
            asset_digest: 9900974715745390a2ae1efd3cd1c383
            seek_keys:
              hisat2_index: 7319f9237651755047bc40d7f7a9770d42a537e840f4e105
            asset_parents: 
             - 7319f9237651755047bc40d7f7a9770d42a537e840f4e105/fasta:default
            archive_digest: 794c9c47cf462947f60862061ffd5a0d
            archive_size: 348.5KB
            asset_size: 4.6MB
            asset_children: []
            legacy_archive_digest: 0fcdb0e5c13953b1262a3500eec26f09
        default_tag: default
      bwa_index:
        asset_description: Genome index for Burrows-Wheeler Alignment Tool, produced with bwa index
        tags:
          default:
            asset_path: bwa_index
            asset_digest: 58073f1e9e77cb2c3b57dc3d26e22e37
            seek_keys:
              bwa_index: 7319f9237651755047bc40d7f7a9770d42a537e840f4e105.fa
            asset_parents: 
             - 7319f9237651755047bc40d7f7a9770d42a537e840f4e105/fasta:default
            archive_digest: 8a4b41778a98e039a9cf3d880c55ccbd
            archive_size: 130.8KB
            asset_size: 253.3KB
            asset_children: []
            legacy_archive_digest: 40c6925806b6fe376e176743116156f3
        default_tag: default
    aliases: 
     - human_repeats
    genome_description: test description human repeats
  94e0d21feb576e6af61cd2a798ad30682ef2428bb7eabbb4:
    assets:
      fasta:
        asset_description: DNA sequences in the FASTA format, indexed FASTA (produced with samtools index) and chromosome sizes file
        tags:
          default:
            asset_path: fasta
            asset_digest: 4eb430296bc02ed7e4006624f1d5ac53
            seek_keys:
              fasta: 94e0d21feb576e6af61cd2a798ad30682ef2428bb7eabbb4.fa
              fai: 94e0d21feb576e6af61cd2a798ad30682ef2428bb7eabbb4.fa.fai
              chrom_sizes: 94e0d21feb576e6af61cd2a798ad30682ef2428bb7eabbb4.chrom.sizes
            asset_parents: []
            asset_children: 
             - 94e0d21feb576e6af61cd2a798ad30682ef2428bb7eabbb4/bowtie2_index:default
            archive_digest: ccf824eb723285db92ab059d8ac2ec95
            archive_size: 8.6KB
            asset_size: 40.6KB
            legacy_archive_digest: cf3d2008d372b6323ad8398bd1ad4f57
        default_tag: default
      bowtie2_index:
        asset_description: Genome index for bowtie, produced with bowtie-build
        tags:
          default:
            asset_path: bowtie2_index
            asset_digest: 1262e30d4a87db9365d501de8559b3b4
            seek_keys:
              bowtie2_index: 94e0d21feb576e6af61cd2a798ad30682ef2428bb7eabbb4
            asset_parents: 
             - 94e0d21feb576e6af61cd2a798ad30682ef2428bb7eabbb4/fasta:default
            archive_digest: eeea620b5efc61cf96ca05420ca45f0f
            archive_size: 117.0KB
            asset_size: 8.1MB
            asset_children: []
            legacy_archive_digest: 4f280a4d6dcae27d987f131be496eab1
        default_tag: default
    aliases: 
     - rCRSd
    genome_description: test description rCRSd
  43f14ba8beed34d52edb244e26f193df6edbb467bd55d37a:
    assets:
      fasta:
        asset_description: DNA sequences in the FASTA format, indexed FASTA (produced with samtools index) and chromosome sizes file
        tags:
          default:
            asset_path: fasta
            asset_digest: 8dfe402f7d29d5b036dd8937119e4404
            seek_keys:
              fasta: 43f14ba8beed34d52edb244e26f193df6edbb467bd55d37a.fa
              fai: 43f14ba8beed34d52edb244e26f193df6edbb467bd55d37a.fa.fai
              chrom_sizes: 43f14ba8beed34d52edb244e26f193df6edbb467bd55d37a.chrom.sizes
            asset_parents: []
            asset_children: 
             - 43f14ba8beed34d52edb244e26f193df6edbb467bd55d37a/bwa_index:default
             - 43f14ba8beed34d52edb244e26f193df6edbb467bd55d37a/bowtie2_index:default
            archive_digest: a104fb7c5da31cff4a343a9724904907
            archive_size: 9.1KB
            asset_size: 40.0KB
            legacy_archive_digest: fd002a12c82fb63b2d4143a825e8aee2
        default_tag: default
      bwa_index:
        asset_description: Genome index for Burrows-Wheeler Alignment Tool, produced with bwa index
        tags:
          default:
            asset_path: bwa_index
            asset_digest: 914dec83dcfab73e056717d33ecfd465
            seek_keys:
              bwa_index: 43f14ba8beed34d52edb244e26f193df6edbb467bd55d37a.fa
            asset_parents: 
             - 43f14ba8beed34d52edb244e26f193df6edbb467bd55d37a/fasta:default
            archive_digest: 3454911cecdaf0ccc589f83138eab7e2
            archive_size: 32.2KB
            asset_size: 62.4KB
            asset_children: []
            legacy_archive_digest: cc08e814f264ecc861d8e45e9daa7b79
        default_tag: default
      bowtie2_index:
        asset_description: Genome index for bowtie, produced with bowtie-build
        tags:
          default:
            asset_path: bowtie2_index
            asset_digest: 738d82a0ff63864726c442b2276d06c0
            seek_keys:
              bowtie2_index: 43f14ba8beed34d52edb244e26f193df6edbb467bd55d37a
            asset_parents: 
             - 43f14ba8beed34d52edb244e26f193df6edbb467bd55d37a/fasta:default
            archive_digest: 2b72e4fc2a2eaa5eefa431926d732e03
            archive_size: 119.7KB
            asset_size: 8.1MB
            asset_children: []
            legacy_archive_digest: 53127ba41caff66f0ef73e656124f5d9
        default_tag: default
    aliases: 
     - mouse_chrM2x
    genome_description: test description mouse chrM2x
remote_url_base: http://awspds.refgenie.databio.org/rg.databio.org/
genome_archive_folder: /project/shefflab//deploy/rg.databio.org/genomes/archive
genome_archive_config: refgenie_config_archive.yaml
