config_version: 0.4
genome_folder: /project/shefflab//deploy/test-data/genomes
genome_servers: ['http://refgenomes.databio.org']
genomes:
  58de7f33a36ccd9d6e3b1b3afe6b9f37cd5b2867bbfb929a:
    assets:
      fasta:
        asset_description: DNA sequences in the FASTA format, indexed FASTA (produced with samtools index) and chromosome sizes file
        tags:
          default:
            asset_path: fasta
            asset_digest: 59fed5ec3c3a95bc5709b24b8f2cf7bf
            seek_keys:
              fasta: 58de7f33a36ccd9d6e3b1b3afe6b9f37cd5b2867bbfb929a.fa
              fai: 58de7f33a36ccd9d6e3b1b3afe6b9f37cd5b2867bbfb929a.fa.fai
              chrom_sizes: 58de7f33a36ccd9d6e3b1b3afe6b9f37cd5b2867bbfb929a.chrom.sizes
            asset_parents: []
            asset_children: ['58de7f33a36ccd9d6e3b1b3afe6b9f37cd5b2867bbfb929a/bowtie2_index:default']
            archive_digest: 534269305b47d8b096975349d843072d
            archive_size: 833.4MB
            asset_size: 2.9GB
            legacy_archive_digest: bd3bfd907ccfb1e1cd0580193927346c
        default_tag: default
      bowtie2_index:
        asset_description: Genome index for bowtie, produced with bowtie-build
        tags:
          default:
            asset_path: bowtie2_index
            asset_digest: 04880a3192a69bbfdc36da25b67203cb
            seek_keys:
              bowtie2_index: 58de7f33a36ccd9d6e3b1b3afe6b9f37cd5b2867bbfb929a
            asset_parents: ['58de7f33a36ccd9d6e3b1b3afe6b9f37cd5b2867bbfb929a/fasta:default']
            archive_digest: c8516e5197776a688e82903ff99c7ec3
            archive_size: 3.5GB
            asset_size: 3.9GB
            asset_children: []
            legacy_archive_digest: 0ac84ad03454e923e7bd357b368af110
        default_tag: default
    aliases: ['hg38']
    genome_description: The GCA_000001405.15 GRCh38_no_alt_analysis_set from NCBI
  ebf26d2f064462bea7029e6b4d2298967d7435bff82ed224:
    assets:
      fasta:
        asset_description: DNA sequences in the FASTA format, indexed FASTA (produced with samtools index) and chromosome sizes file
        tags:
          default:
            asset_path: fasta
            asset_digest: 4a749d4e74b057d0efa0c8398ebcb871
            seek_keys:
              fasta: ebf26d2f064462bea7029e6b4d2298967d7435bff82ed224.fa
              fai: ebf26d2f064462bea7029e6b4d2298967d7435bff82ed224.fa.fai
              chrom_sizes: ebf26d2f064462bea7029e6b4d2298967d7435bff82ed224.chrom.sizes
            asset_parents: []
            asset_children: ['ebf26d2f064462bea7029e6b4d2298967d7435bff82ed224/bwa_index:default', 'ebf26d2f064462bea7029e6b4d2298967d7435bff82ed224/hisat2_index:default']
            archive_digest: 979d0f6b824b7dd40869a7393946d3a7
            archive_size: 33.7KB
            asset_size: 154.0KB
            legacy_archive_digest: c0c01f5fa3fb780136e14c1e0f924221
        default_tag: default
      bwa_index:
        asset_description: Genome index for Burrows-Wheeler Alignment Tool, produced with bwa index
        tags:
          default:
            asset_path: bwa_index
            asset_digest: 58073f1e9e77cb2c3b57dc3d26e22e37
            seek_keys:
              bwa_index: ebf26d2f064462bea7029e6b4d2298967d7435bff82ed224.fa
            asset_parents: ['ebf26d2f064462bea7029e6b4d2298967d7435bff82ed224/fasta:default']
            archive_digest: 1c8a7d5cdb8dc8246adc548f7dd9e6f7
            archive_size: 163.9KB
            asset_size: 252.5KB
            asset_children: []
            legacy_archive_digest: 180505a12540cc112e68febb15dc10f7
        default_tag: default
      hisat2_index:
        asset_description: Genome index for HISAT2, produced with hisat2-build
        tags:
          default:
            asset_path: hisat2_index
            asset_digest: 9900974715745390a2ae1efd3cd1c383
            seek_keys:
              hisat2_index: ebf26d2f064462bea7029e6b4d2298967d7435bff82ed224
            asset_parents: ['ebf26d2f064462bea7029e6b4d2298967d7435bff82ed224/fasta:default']
            archive_digest: 148482568232e7c475123691f40c9ac0
            archive_size: 348.5KB
            asset_size: 4.6MB
            asset_children: []
            legacy_archive_digest: 650c0639750e4cf47195692f78424721
        default_tag: default
    aliases: ['human_repeats']
    genome_description: Manually curated collection of human repeat sequences from GenBank
  511fb1178275e7d529560d53b949dba40815f195623bce8e:
    assets:
      fasta:
        asset_description: DNA sequences in the FASTA format, indexed FASTA (produced with samtools index) and chromosome sizes file
        tags:
          default:
            asset_path: fasta
            asset_digest: 4eb430296bc02ed7e4006624f1d5ac53
            seek_keys:
              fasta: 511fb1178275e7d529560d53b949dba40815f195623bce8e.fa
              fai: 511fb1178275e7d529560d53b949dba40815f195623bce8e.fa.fai
              chrom_sizes: 511fb1178275e7d529560d53b949dba40815f195623bce8e.chrom.sizes
            asset_parents: []
            asset_children: ['511fb1178275e7d529560d53b949dba40815f195623bce8e/bowtie2_index:default']
            archive_digest: 9a094bc995240797d24c7deb8cd9e4b6
            archive_size: 8.7KB
            asset_size: 42.2KB
            legacy_archive_digest: 62cd68ac1fdc3255e9ad2703bdee24ed
        default_tag: default
      bowtie2_index:
        asset_description: Genome index for bowtie, produced with bowtie-build
        tags:
          default:
            asset_path: bowtie2_index
            asset_digest: 1262e30d4a87db9365d501de8559b3b4
            seek_keys:
              bowtie2_index: 511fb1178275e7d529560d53b949dba40815f195623bce8e
            asset_parents: ['511fb1178275e7d529560d53b949dba40815f195623bce8e/fasta:default']
            archive_digest: b2d54471e87474026ed165d732fb301a
            archive_size: 117.3KB
            asset_size: 8.1MB
            asset_children: []
            legacy_archive_digest: 9eca00ecd015c53c6bc7d0d91a02ac0e
        default_tag: default
    aliases: ['rCRSd']
    genome_description: The revised cambridge reference sequence. This is the human mitochondrial reference genome
  194f8681e3d9e35b9eca2d17ec5e36bbf5e8c2beea486496:
    assets:
      fasta:
        asset_description: DNA sequences in the FASTA format, indexed FASTA (produced with samtools index) and chromosome sizes file
        tags:
          default:
            asset_path: fasta
            asset_digest: 8dfe402f7d29d5b036dd8937119e4404
            seek_keys:
              fasta: 194f8681e3d9e35b9eca2d17ec5e36bbf5e8c2beea486496.fa
              fai: 194f8681e3d9e35b9eca2d17ec5e36bbf5e8c2beea486496.fa.fai
              chrom_sizes: 194f8681e3d9e35b9eca2d17ec5e36bbf5e8c2beea486496.chrom.sizes
            asset_parents: []
            asset_children: ['194f8681e3d9e35b9eca2d17ec5e36bbf5e8c2beea486496/bwa_index:default', '194f8681e3d9e35b9eca2d17ec5e36bbf5e8c2beea486496/bowtie2_index:default']
            archive_digest: 7260f11f8d5d3898bf969e804712b43e
            archive_size: 9.0KB
            asset_size: 41.8KB
            legacy_archive_digest: e7159e01c51042e21c11c378735f680f
        default_tag: default
      bwa_index:
        asset_description: Genome index for Burrows-Wheeler Alignment Tool, produced with bwa index
        tags:
          default:
            asset_path: bwa_index
            asset_digest: 914dec83dcfab73e056717d33ecfd465
            seek_keys:
              bwa_index: 194f8681e3d9e35b9eca2d17ec5e36bbf5e8c2beea486496.fa
            asset_parents: ['194f8681e3d9e35b9eca2d17ec5e36bbf5e8c2beea486496/fasta:default']
            archive_digest: 42c0636446ffe5bf6a33015faeb941c6
            archive_size: 41.5KB
            asset_size: 64.0KB
            asset_children: []
            legacy_archive_digest: 9587fc5818e168b9c4aaf7eef840fb27
        default_tag: default
      bowtie2_index:
        asset_description: Genome index for bowtie, produced with bowtie-build
        tags:
          default:
            asset_path: bowtie2_index
            asset_digest: 738d82a0ff63864726c442b2276d06c0
            seek_keys:
              bowtie2_index: 194f8681e3d9e35b9eca2d17ec5e36bbf5e8c2beea486496
            asset_parents: ['194f8681e3d9e35b9eca2d17ec5e36bbf5e8c2beea486496/fasta:default']
            archive_digest: bc18e75a6877680a92cec48ea0a15d37
            archive_size: 119.9KB
            asset_size: 8.1MB
            asset_children: []
            legacy_archive_digest: 77bce136d6bd4b092957563ce725fb91
        default_tag: default
    aliases: ['mouse_chrM2x']
    genome_description: The mouse mitochondrial genome, doubled
remote_url_base: http://awspds.refgenie.databio.org/test-data/
genome_archive_folder: /project/shefflab//deploy/test-data/genomes/archive
genome_archive_config: refgenie_config_archive.yaml
