config_version: 0.4
genome_folder: /project/shefflab//deploy/test-data/genomes
genome_servers: ['http://refgenomes.databio.org']
remote_url_base: https://refgenie.s3.amazonaws.com/test-data/
genome_archive_folder: /project/shefflab//deploy/test-data/genomes/archive
genome_archive_config: refgenie_config_archive.yaml
genomes:
  58de7f33a36ccd9d6e3b1b3afe6b9f37cd5b2867bbfb929a:
    assets:
      fasta:
        asset_description: DNA sequences in the FASTA format, indexed FASTA (produced with samtools index) and chromosome sizes file
        tags:
          default:
            asset_path: fasta
            asset_digest: 59fed5ec3c3a95bc5709b24b8f2cf7bf
            seek_keys:
              fasta: 58de7f33a36ccd9d6e3b1b3afe6b9f37cd5b2867bbfb929a.fa
              fai: 58de7f33a36ccd9d6e3b1b3afe6b9f37cd5b2867bbfb929a.fa.fai
              chrom_sizes: 58de7f33a36ccd9d6e3b1b3afe6b9f37cd5b2867bbfb929a.chrom.sizes
            asset_parents: []
            archive_digest: 93d2f10ba4a96670728cf2181c60cfcd
            archive_size: 833.4MB
            asset_size: 2.9GB
            asset_children: ['58de7f33a36ccd9d6e3b1b3afe6b9f37cd5b2867bbfb929a/bowtie2_index:default']
        default_tag: default
      bowtie2_index:
        asset_description: Genome index for bowtie, produced with bowtie-build
        default_tag: default
        tags:
          default:
            asset_path: bowtie2_index
            seek_keys:
              bowtie2_index: 58de7f33a36ccd9d6e3b1b3afe6b9f37cd5b2867bbfb929a
            archive_digest: d28afb81fe82dfb080d8551c2f966745
            archive_size: 3.5GB
            asset_size: 3.9GB
            asset_parents: ['58de7f33a36ccd9d6e3b1b3afe6b9f37cd5b2867bbfb929a/fasta:default']
            asset_children: []
            asset_digest: 04880a3192a69bbfdc36da25b67203cb
    aliases: ['hg38']
    genome_description: test
  ebf26d2f064462bea7029e6b4d2298967d7435bff82ed224:
    assets:
      fasta:
        asset_description: DNA sequences in the FASTA format, indexed FASTA (produced with samtools index) and chromosome sizes file
        tags:
          default:
            asset_path: fasta
            asset_digest: 4a749d4e74b057d0efa0c8398ebcb871
            seek_keys:
              fasta: ebf26d2f064462bea7029e6b4d2298967d7435bff82ed224.fa
              fai: ebf26d2f064462bea7029e6b4d2298967d7435bff82ed224.fa.fai
              chrom_sizes: ebf26d2f064462bea7029e6b4d2298967d7435bff82ed224.chrom.sizes
            asset_parents: []
            asset_children: ['ebf26d2f064462bea7029e6b4d2298967d7435bff82ed224/bwa_index:default', 'ebf26d2f064462bea7029e6b4d2298967d7435bff82ed224/hisat2_index:default']
            archive_digest: 0cfc0adcb3de188681832cd1e34d5dac
            archive_size: 33.7KB
            asset_size: 154.0KB
        default_tag: default
      bwa_index:
        asset_description: Genome index for Burrows-Wheeler Alignment Tool, produced with bwa index
        tags:
          default:
            asset_path: bwa_index
            asset_digest: 58073f1e9e77cb2c3b57dc3d26e22e37
            seek_keys:
              bwa_index: ebf26d2f064462bea7029e6b4d2298967d7435bff82ed224.fa
            asset_parents: ['ebf26d2f064462bea7029e6b4d2298967d7435bff82ed224/fasta:default']
            archive_digest: 748b01437909d4067b7ac9a7b33305a8
            archive_size: 163.9KB
            asset_size: 252.5KB
            asset_children: []
        default_tag: default
      hisat2_index:
        asset_description: Genome index for HISAT2, produced with hisat2-build
        tags:
          default:
            asset_path: hisat2_index
            asset_digest: 9900974715745390a2ae1efd3cd1c383
            seek_keys:
              hisat2_index: ebf26d2f064462bea7029e6b4d2298967d7435bff82ed224
            asset_parents: ['ebf26d2f064462bea7029e6b4d2298967d7435bff82ed224/fasta:default']
            archive_digest: 4119e5fea988b8a1de5957c224f5264d
            archive_size: 348.5KB
            asset_size: 4.6MB
            asset_children: []
        default_tag: default
    aliases: ['human_repeats']
    genome_description: test
  511fb1178275e7d529560d53b949dba40815f195623bce8e:
    assets:
      fasta:
        asset_description: DNA sequences in the FASTA format, indexed FASTA (produced with samtools index) and chromosome sizes file
        tags:
          default:
            asset_path: fasta
            asset_digest: 4eb430296bc02ed7e4006624f1d5ac53
            seek_keys:
              fasta: 511fb1178275e7d529560d53b949dba40815f195623bce8e.fa
              fai: 511fb1178275e7d529560d53b949dba40815f195623bce8e.fa.fai
              chrom_sizes: 511fb1178275e7d529560d53b949dba40815f195623bce8e.chrom.sizes
            asset_parents: []
            asset_children: ['511fb1178275e7d529560d53b949dba40815f195623bce8e/bowtie2_index:default']
            archive_digest: fd5cb220a885f5d48bba110835171089
            archive_size: 8.7KB
            asset_size: 42.2KB
        default_tag: default
      bowtie2_index:
        asset_description: Genome index for bowtie, produced with bowtie-build
        tags:
          default:
            asset_path: bowtie2_index
            asset_digest: 1262e30d4a87db9365d501de8559b3b4
            seek_keys:
              bowtie2_index: 511fb1178275e7d529560d53b949dba40815f195623bce8e
            asset_parents: ['511fb1178275e7d529560d53b949dba40815f195623bce8e/fasta:default']
            archive_digest: f2ade1e3df9d8bdc400f4dcfd6edd6bd
            archive_size: 117.3KB
            asset_size: 8.1MB
            asset_children: []
        default_tag: default
    aliases: ['rCRSd']
    genome_description: test
  194f8681e3d9e35b9eca2d17ec5e36bbf5e8c2beea486496:
    assets:
      fasta:
        asset_description: DNA sequences in the FASTA format, indexed FASTA (produced with samtools index) and chromosome sizes file
        tags:
          default:
            asset_path: fasta
            asset_digest: 8dfe402f7d29d5b036dd8937119e4404
            seek_keys:
              fasta: 194f8681e3d9e35b9eca2d17ec5e36bbf5e8c2beea486496.fa
              fai: 194f8681e3d9e35b9eca2d17ec5e36bbf5e8c2beea486496.fa.fai
              chrom_sizes: 194f8681e3d9e35b9eca2d17ec5e36bbf5e8c2beea486496.chrom.sizes
            asset_parents: []
            asset_children: ['194f8681e3d9e35b9eca2d17ec5e36bbf5e8c2beea486496/bwa_index:default', '194f8681e3d9e35b9eca2d17ec5e36bbf5e8c2beea486496/bowtie2_index:default']
            archive_digest: 9bee27c26bec35ac5b16eb8ab92b537a
            archive_size: 9.0KB
            asset_size: 41.8KB
        default_tag: default
      bwa_index:
        asset_description: Genome index for Burrows-Wheeler Alignment Tool, produced with bwa index
        tags:
          default:
            asset_path: bwa_index
            asset_digest: 914dec83dcfab73e056717d33ecfd465
            seek_keys:
              bwa_index: 194f8681e3d9e35b9eca2d17ec5e36bbf5e8c2beea486496.fa
            asset_parents: ['194f8681e3d9e35b9eca2d17ec5e36bbf5e8c2beea486496/fasta:default']
            archive_digest: 4c61c55ceed4ba6459a4f8e2f204eb84
            archive_size: 41.6KB
            asset_size: 64.0KB
            asset_children: []
        default_tag: default
      bowtie2_index:
        asset_description: Genome index for bowtie, produced with bowtie-build
        tags:
          default:
            asset_path: bowtie2_index
            asset_digest: 738d82a0ff63864726c442b2276d06c0
            seek_keys:
              bowtie2_index: 194f8681e3d9e35b9eca2d17ec5e36bbf5e8c2beea486496
            asset_parents: ['194f8681e3d9e35b9eca2d17ec5e36bbf5e8c2beea486496/fasta:default']
            archive_digest: 5744a7e3162b24907a76bb5d2d2386c4
            archive_size: 119.9KB
            asset_size: 8.1MB
            asset_children: []
        default_tag: default
    aliases: ['mouse_chrM2x']
    genome_description: test
