config_version: 0.4
genome_folder: /project/shefflab//deploy/rg.databio.org/genomes
genome_servers: 
 - http://refgenomes.databio.org
remotes:
  http:
    prefix: http://awspds.refgenie.databio.org/rg.databio.org/
    description: HTTP compatible path
  s3:
    prefix: s3://awspds.refgenie.databio.org/rg.databio.org/
    description: S3 compatible path
genomes:
  94e0d21feb576e6af61cd2a798ad30682ef2428bb7eabbb4:
    assets:
      fasta:
        asset_description: DNA sequences in the FASTA format, indexed FASTA (produced with samtools index) and chromosome sizes file
        tags:
          default:
            asset_path: fasta
            asset_digest: 4eb430296bc02ed7e4006624f1d5ac53
            seek_keys:
              fasta: 94e0d21feb576e6af61cd2a798ad30682ef2428bb7eabbb4.fa
              fai: 94e0d21feb576e6af61cd2a798ad30682ef2428bb7eabbb4.fa.fai
              chrom_sizes: 94e0d21feb576e6af61cd2a798ad30682ef2428bb7eabbb4.chrom.sizes
              dir: .
            asset_parents: []
            asset_children: 
             - 94e0d21feb576e6af61cd2a798ad30682ef2428bb7eabbb4/bowtie2_index:default
             - 94e0d21feb576e6af61cd2a798ad30682ef2428bb7eabbb4/salmon_index:default
             - 94e0d21feb576e6af61cd2a798ad30682ef2428bb7eabbb4/bismark_bt2_index:default
            archive_digest: f64cc334c8c694e47faaeb77b0abb112
            archive_size: 8.6KB
            asset_size: 39.9KB
            legacy_archive_digest: 8b1492d826c5ccea0285e7ee845162aa
        default_tag: default
      bowtie2_index:
        asset_description: Genome index for bowtie, produced with bowtie-build
        tags:
          default:
            asset_path: bowtie2_index
            asset_digest: 1262e30d4a87db9365d501de8559b3b4
            seek_keys:
              bowtie2_index: 94e0d21feb576e6af61cd2a798ad30682ef2428bb7eabbb4
              dir: .
            asset_parents: 
             - 94e0d21feb576e6af61cd2a798ad30682ef2428bb7eabbb4/fasta:default
            archive_digest: 4ffca9c7d255257f57fc38b7166dcdad
            archive_size: 117.0KB
            asset_size: 8.1MB
            asset_children: []
            legacy_archive_digest: c31a12dc62f2ee6576e88b18b4eba3be
        default_tag: default
      salmon_index:
        asset_description: Transcriptome index for salmon, produced with salmon index
        tags:
          default:
            asset_path: salmon_index
            asset_digest: 74a0e463d958e7d6d070e656cdd84d45
            seek_keys:
              salmon_index: .
              dir: .
            asset_parents: 
             - 94e0d21feb576e6af61cd2a798ad30682ef2428bb7eabbb4/fasta:default
            archive_digest: a32873b621d401b4f87ed0214dd75deb
            archive_size: 53.9KB
            asset_size: 149.0KB
            asset_children: []
            legacy_archive_digest: e9892c3d5f5d3484eaf7c7f415d8bff0
        default_tag: default
      bismark_bt2_index:
        asset_description: Genome index for Bisulfite-Seq applications, produced by bismark_genome_preparation using bowtie2
        tags:
          default:
            asset_path: bismark_bt2_index
            asset_digest: 0caeadefe17f77826e99cb4036a994ed
            seek_keys:
              bismark_bt2_index: .
              dir: .
            asset_parents: 
             - 94e0d21feb576e6af61cd2a798ad30682ef2428bb7eabbb4/fasta:default
            archive_digest: 5cdf5da4b23ea74a89d64362da974e96
            archive_size: 193.2KB
            asset_size: 16.2MB
            asset_children: []
            legacy_archive_digest: 599b38e253dde8a20f4c34405eea6de1
        default_tag: default
    aliases: 
     - rCRSd
    genome_description: test description rCRSd
  7319f9237651755047bc40d7f7a9770d42a537e840f4e105:
    assets:
      fasta:
        asset_description: DNA sequences in the FASTA format, indexed FASTA (produced with samtools index) and chromosome sizes file
        tags:
          default:
            asset_path: fasta
            asset_digest: 4a749d4e74b057d0efa0c8398ebcb871
            seek_keys:
              fasta: 7319f9237651755047bc40d7f7a9770d42a537e840f4e105.fa
              fai: 7319f9237651755047bc40d7f7a9770d42a537e840f4e105.fa.fai
              chrom_sizes: 7319f9237651755047bc40d7f7a9770d42a537e840f4e105.chrom.sizes
              dir: .
            asset_parents: []
            asset_children: 
             - 7319f9237651755047bc40d7f7a9770d42a537e840f4e105/bwa_index:default
             - 7319f9237651755047bc40d7f7a9770d42a537e840f4e105/hisat2_index:default
            archive_digest: a7f5c18c05ead91593abd3a534630603
            archive_size: 33.8KB
            asset_size: 154.2KB
            legacy_archive_digest: 0ccedc6e0e14e12b4d54db33b35ef4f7
        default_tag: default
      bwa_index:
        asset_description: Genome index for Burrows-Wheeler Alignment Tool, produced with bwa index
        tags:
          default:
            asset_path: bwa_index
            asset_digest: 58073f1e9e77cb2c3b57dc3d26e22e37
            seek_keys:
              bwa_index: 7319f9237651755047bc40d7f7a9770d42a537e840f4e105.fa
              dir: .
            asset_parents: 
             - 7319f9237651755047bc40d7f7a9770d42a537e840f4e105/fasta:default
            archive_digest: 2384d87244996ff2c44cc7e6f50b55bb
            archive_size: 130.8KB
            asset_size: 252.7KB
            asset_children: []
            legacy_archive_digest: 88b64fc776da424b098cebf094cfa637
        default_tag: default
      hisat2_index:
        asset_description: Genome index for HISAT2, produced with hisat2-build
        tags:
          default:
            asset_path: hisat2_index
            asset_digest: 9900974715745390a2ae1efd3cd1c383
            seek_keys:
              hisat2_index: 7319f9237651755047bc40d7f7a9770d42a537e840f4e105
              dir: .
            asset_parents: 
             - 7319f9237651755047bc40d7f7a9770d42a537e840f4e105/fasta:default
            archive_digest: 9d16a0c29f8f5db94ad53820ed9bedd2
            archive_size: 348.6KB
            asset_size: 4.6MB
            asset_children: []
            legacy_archive_digest: 9f5da94bf1a8a0e60aa38e50c5567675
        default_tag: default
    aliases: 
     - human_repeats
    genome_description: test description human repeats
  43f14ba8beed34d52edb244e26f193df6edbb467bd55d37a:
    assets:
      fasta:
        asset_description: DNA sequences in the FASTA format, indexed FASTA (produced with samtools index) and chromosome sizes file
        tags:
          default:
            asset_path: fasta
            asset_digest: 8dfe402f7d29d5b036dd8937119e4404
            seek_keys:
              fasta: 43f14ba8beed34d52edb244e26f193df6edbb467bd55d37a.fa
              fai: 43f14ba8beed34d52edb244e26f193df6edbb467bd55d37a.fa.fai
              chrom_sizes: 43f14ba8beed34d52edb244e26f193df6edbb467bd55d37a.chrom.sizes
              dir: .
            asset_parents: []
            asset_children: 
             - 43f14ba8beed34d52edb244e26f193df6edbb467bd55d37a/bwa_index:default
             - 43f14ba8beed34d52edb244e26f193df6edbb467bd55d37a/bowtie2_index:default
            archive_digest: 50de20ae9e13ccb8d8cbad79f360e272
            archive_size: 9.1KB
            asset_size: 39.4KB
            legacy_archive_digest: 104d77ad2ec855ad4060687ed699e524
        default_tag: default
      bwa_index:
        asset_description: Genome index for Burrows-Wheeler Alignment Tool, produced with bwa index
        tags:
          default:
            asset_path: bwa_index
            asset_digest: 914dec83dcfab73e056717d33ecfd465
            seek_keys:
              bwa_index: 43f14ba8beed34d52edb244e26f193df6edbb467bd55d37a.fa
              dir: .
            asset_parents: 
             - 43f14ba8beed34d52edb244e26f193df6edbb467bd55d37a/fasta:default
            archive_digest: 72bd61909c03ff4b75626db9fdef69ae
            archive_size: 32.2KB
            asset_size: 61.8KB
            asset_children: []
            legacy_archive_digest: 16ebac5f1fe6e09ef4dbe4119cf65b92
        default_tag: default
      bowtie2_index:
        asset_description: Genome index for bowtie, produced with bowtie-build
        tags:
          default:
            asset_path: bowtie2_index
            asset_digest: 738d82a0ff63864726c442b2276d06c0
            seek_keys:
              bowtie2_index: 43f14ba8beed34d52edb244e26f193df6edbb467bd55d37a
              dir: .
            asset_parents: 
             - 43f14ba8beed34d52edb244e26f193df6edbb467bd55d37a/fasta:default
            archive_digest: 4ca7d55ae839f3a98773ade837de7841
            archive_size: 119.7KB
            asset_size: 8.1MB
            asset_children: []
            legacy_archive_digest: fd42bee217868694385ed8f8756db14d
        default_tag: default
    aliases: 
     - mouse_chrM2x
    genome_description: test description mouse chrM2x
  2230c535660fb4774114bfa966a62f823fdb6d21acf138d4:
    assets:
      fasta:
        asset_description: DNA sequences in the FASTA format, indexed FASTA (produced with samtools index) and chromosome sizes file
        tags:
          default:
            asset_path: fasta
            asset_digest: 59fed5ec3c3a95bc5709b24b8f2cf7bf
            seek_keys:
              fasta: 2230c535660fb4774114bfa966a62f823fdb6d21acf138d4.fa
              fai: 2230c535660fb4774114bfa966a62f823fdb6d21acf138d4.fa.fai
              chrom_sizes: 2230c535660fb4774114bfa966a62f823fdb6d21acf138d4.chrom.sizes
              dir: .
            asset_parents: []
            asset_children: 
             - 2230c535660fb4774114bfa966a62f823fdb6d21acf138d4/bowtie2_index:default
        default_tag: default
      bowtie2_index:
        asset_description: Genome index for bowtie, produced with bowtie-build
        tags:
          default:
            asset_path: bowtie2_index
            asset_digest: 04880a3192a69bbfdc36da25b67203cb
            seek_keys:
              bowtie2_index: 2230c535660fb4774114bfa966a62f823fdb6d21acf138d4
              dir: .
            asset_parents: 
             - 2230c535660fb4774114bfa966a62f823fdb6d21acf138d4/fasta:default
        default_tag: default
    aliases: 
     - hg38
    genome_description: test description hg38
genome_archive_folder: /project/shefflab//deploy/rg.databio.org/genomes/archive
genome_archive_config: refgenie_config_archive.yaml
