config_version: 0.4
genome_folder: /project/shefflab//deploy/rg.databio.org/genomes
genome_servers: 
 - http://refgenomes.databio.org
remotes:
  http:
    prefix: http://awspds.refgenie.databio.org/rg.databio.org/
    description: Serves HTTP compatible path
  s3:
    prefix: s3://awspds.refgenie.databio.org/rg.databio.org/
    description: Serves S3 compatible path
genomes:
  94e0d21feb576e6af61cd2a798ad30682ef2428bb7eabbb4:
    assets:
      fasta:
        asset_description: DNA sequences in the FASTA format, indexed FASTA (produced with samtools index) and chromosome sizes file
        tags:
          default:
            asset_path: fasta
            asset_digest: 4eb430296bc02ed7e4006624f1d5ac53
            seek_keys:
              fasta: 94e0d21feb576e6af61cd2a798ad30682ef2428bb7eabbb4.fa
              fai: 94e0d21feb576e6af61cd2a798ad30682ef2428bb7eabbb4.fa.fai
              chrom_sizes: 94e0d21feb576e6af61cd2a798ad30682ef2428bb7eabbb4.chrom.sizes
              dir: .
            asset_parents: []
            asset_children: 
             - 94e0d21feb576e6af61cd2a798ad30682ef2428bb7eabbb4/bowtie2_index:default
            archive_digest: 6ee360248403e0db37f22334fe0e9d70
            archive_size: 8.6KB
            asset_size: 39.9KB
            legacy_archive_digest: 4100a8f62dc9b8c069e355a6d3b42712
        default_tag: default
      bowtie2_index:
        asset_description: Genome index for bowtie, produced with bowtie-build
        tags:
          default:
            asset_path: bowtie2_index
            asset_digest: 1262e30d4a87db9365d501de8559b3b4
            seek_keys:
              bowtie2_index: 94e0d21feb576e6af61cd2a798ad30682ef2428bb7eabbb4
              dir: .
            asset_parents: 
             - 94e0d21feb576e6af61cd2a798ad30682ef2428bb7eabbb4/fasta:default
            archive_digest: 5f22ab112f89c8efc577f5f1f8b1298b
            archive_size: 117.0KB
            asset_size: 8.1MB
            asset_children: []
            legacy_archive_digest: 7e26f6e778c291fee173d2aa59bf1914
        default_tag: default
    aliases: 
     - rCRSd
    genome_description: test description rCRSd
  7319f9237651755047bc40d7f7a9770d42a537e840f4e105:
    assets:
      fasta:
        asset_description: DNA sequences in the FASTA format, indexed FASTA (produced with samtools index) and chromosome sizes file
        tags:
          default:
            asset_path: fasta
            asset_digest: 4a749d4e74b057d0efa0c8398ebcb871
            seek_keys:
              fasta: 7319f9237651755047bc40d7f7a9770d42a537e840f4e105.fa
              fai: 7319f9237651755047bc40d7f7a9770d42a537e840f4e105.fa.fai
              chrom_sizes: 7319f9237651755047bc40d7f7a9770d42a537e840f4e105.chrom.sizes
              dir: .
            asset_parents: []
            asset_children: 
             - 7319f9237651755047bc40d7f7a9770d42a537e840f4e105/bwa_index:default
             - 7319f9237651755047bc40d7f7a9770d42a537e840f4e105/hisat2_index:default
            archive_digest: 703a1aea7ee3450462767566b4dfbb2c
            archive_size: 33.8KB
            asset_size: 154.2KB
            legacy_archive_digest: b6c51bdde88d4bbd04a0bcb0e3f0a098
        default_tag: default
      bwa_index:
        asset_description: Genome index for Burrows-Wheeler Alignment Tool, produced with bwa index
        tags:
          default:
            asset_path: bwa_index
            asset_digest: 58073f1e9e77cb2c3b57dc3d26e22e37
            seek_keys:
              bwa_index: 7319f9237651755047bc40d7f7a9770d42a537e840f4e105.fa
              dir: .
            asset_parents: 
             - 7319f9237651755047bc40d7f7a9770d42a537e840f4e105/fasta:default
            archive_digest: e18c00ce4923b919c7a9ea6efaf60569
            archive_size: 130.8KB
            asset_size: 252.7KB
            asset_children: []
            legacy_archive_digest: ecba30c1180b7a37de284538efff3c76
        default_tag: default
      hisat2_index:
        asset_description: Genome index for HISAT2, produced with hisat2-build
        tags:
          default:
            asset_path: hisat2_index
            asset_digest: 9900974715745390a2ae1efd3cd1c383
            seek_keys:
              hisat2_index: 7319f9237651755047bc40d7f7a9770d42a537e840f4e105
              dir: .
            asset_parents: 
             - 7319f9237651755047bc40d7f7a9770d42a537e840f4e105/fasta:default
            archive_digest: 5559f6fab087c1dd673188b5d7ba792c
            archive_size: 348.6KB
            asset_size: 4.6MB
            asset_children: []
            legacy_archive_digest: 4c01503af7b3e975b926af85d9661e9a
        default_tag: default
    aliases: 
     - human_repeats
    genome_description: test description human repeats
  43f14ba8beed34d52edb244e26f193df6edbb467bd55d37a:
    assets:
      fasta:
        asset_description: DNA sequences in the FASTA format, indexed FASTA (produced with samtools index) and chromosome sizes file
        tags:
          default:
            asset_path: fasta
            asset_digest: 8dfe402f7d29d5b036dd8937119e4404
            seek_keys:
              fasta: 43f14ba8beed34d52edb244e26f193df6edbb467bd55d37a.fa
              fai: 43f14ba8beed34d52edb244e26f193df6edbb467bd55d37a.fa.fai
              chrom_sizes: 43f14ba8beed34d52edb244e26f193df6edbb467bd55d37a.chrom.sizes
              dir: .
            asset_parents: []
            asset_children: 
             - 43f14ba8beed34d52edb244e26f193df6edbb467bd55d37a/bwa_index:default
             - 43f14ba8beed34d52edb244e26f193df6edbb467bd55d37a/bowtie2_index:default
            archive_digest: 22287d11e296ac656626f1b738fc40a4
            archive_size: 9.1KB
            asset_size: 39.4KB
            legacy_archive_digest: 8692b23bbc2bdd64da7f1e785f6b2ff1
        default_tag: default
      bwa_index:
        asset_description: Genome index for Burrows-Wheeler Alignment Tool, produced with bwa index
        tags:
          default:
            asset_path: bwa_index
            asset_digest: 914dec83dcfab73e056717d33ecfd465
            seek_keys:
              bwa_index: 43f14ba8beed34d52edb244e26f193df6edbb467bd55d37a.fa
              dir: .
            asset_parents: 
             - 43f14ba8beed34d52edb244e26f193df6edbb467bd55d37a/fasta:default
            archive_digest: bbc24956fdbc77a5e3a18d56cd667fa8
            archive_size: 32.2KB
            asset_size: 61.8KB
            asset_children: []
            legacy_archive_digest: 2600fa18c90e2bbd3dae2e9ed999020d
        default_tag: default
      bowtie2_index:
        asset_description: Genome index for bowtie, produced with bowtie-build
        tags:
          default:
            asset_path: bowtie2_index
            asset_digest: 738d82a0ff63864726c442b2276d06c0
            seek_keys:
              bowtie2_index: 43f14ba8beed34d52edb244e26f193df6edbb467bd55d37a
              dir: .
            asset_parents: 
             - 43f14ba8beed34d52edb244e26f193df6edbb467bd55d37a/fasta:default
            archive_digest: 23bd181e6504cbf7abd817d2ea67d16b
            archive_size: 119.7KB
            asset_size: 8.1MB
            asset_children: []
            legacy_archive_digest: 116eadb62e2d8f4cc65b8855574c6d67
        default_tag: default
    aliases: 
     - mouse_chrM2x
    genome_description: test description mouse chrM2x
  2230c535660fb4774114bfa966a62f823fdb6d21acf138d4:
    assets:
      fasta:
        asset_description: DNA sequences in the FASTA format, indexed FASTA (produced with samtools index) and chromosome sizes file
        tags:
          default:
            asset_path: fasta
            asset_digest: 59fed5ec3c3a95bc5709b24b8f2cf7bf
            seek_keys:
              fasta: 2230c535660fb4774114bfa966a62f823fdb6d21acf138d4.fa
              fai: 2230c535660fb4774114bfa966a62f823fdb6d21acf138d4.fa.fai
              chrom_sizes: 2230c535660fb4774114bfa966a62f823fdb6d21acf138d4.chrom.sizes
              dir: .
            asset_parents: []
            archive_digest: ad4d856a3b7600724bcb8ad9459683b5
            archive_size: 833.4MB
            asset_size: 2.9GB
            asset_children: 
             - 2230c535660fb4774114bfa966a62f823fdb6d21acf138d4/bowtie2_index:default
            legacy_archive_digest: 8bfc852046a89b2c59144e85fa8fffd5
        default_tag: default
      bowtie2_index:
        asset_description: Genome index for bowtie, produced with bowtie-build
        default_tag: default
        tags:
          default:
            asset_path: bowtie2_index
            seek_keys:
              bowtie2_index: 2230c535660fb4774114bfa966a62f823fdb6d21acf138d4
              dir: .
            archive_digest: 2dd715c3f994b51333bd25d3493cf7ca
            archive_size: 3.5GB
            asset_size: 3.9GB
            asset_parents: 
             - 2230c535660fb4774114bfa966a62f823fdb6d21acf138d4/fasta:default
            asset_children: []
            asset_digest: 04880a3192a69bbfdc36da25b67203cb
            legacy_archive_digest: 7620ef14b08b21838d0754e7b6665305
    aliases: 
     - hg38
    genome_description: test description hg38
genome_archive_folder: /project/shefflab//deploy/rg.databio.org/genomes/archive
genome_archive_config: refgenie_config_archive.yaml
