config_version: 0.4
genome_folder: /project/shefflab//deploy/rg.databio.org/genomes
genome_servers: 
 - http://refgenomes.databio.org
genomes:
  94e0d21feb576e6af61cd2a798ad30682ef2428bb7eabbb4:
    assets:
      fasta:
        asset_description: DNA sequences in the FASTA format, indexed FASTA (produced with samtools index) and chromosome sizes file
        tags:
          default:
            asset_path: fasta
            asset_digest: 4eb430296bc02ed7e4006624f1d5ac53
            seek_keys:
              fasta: 94e0d21feb576e6af61cd2a798ad30682ef2428bb7eabbb4.fa
              fai: 94e0d21feb576e6af61cd2a798ad30682ef2428bb7eabbb4.fa.fai
              chrom_sizes: 94e0d21feb576e6af61cd2a798ad30682ef2428bb7eabbb4.chrom.sizes
              dir: .
            asset_parents: []
            asset_children: 
             - 94e0d21feb576e6af61cd2a798ad30682ef2428bb7eabbb4/bowtie2_index:default
        default_tag: default
      bowtie2_index:
        asset_description: Genome index for bowtie, produced with bowtie-build
        tags:
          default:
            asset_path: bowtie2_index
            asset_digest: 1262e30d4a87db9365d501de8559b3b4
            seek_keys:
              bowtie2_index: 94e0d21feb576e6af61cd2a798ad30682ef2428bb7eabbb4
              dir: .
            asset_parents: 
             - 94e0d21feb576e6af61cd2a798ad30682ef2428bb7eabbb4/fasta:default
        default_tag: default
    aliases: 
     - rCRSd
    genome_description: test description rCRSd
  7319f9237651755047bc40d7f7a9770d42a537e840f4e105:
    assets:
      fasta:
        asset_description: DNA sequences in the FASTA format, indexed FASTA (produced with samtools index) and chromosome sizes file
        tags:
          default:
            asset_path: fasta
            asset_digest: 4a749d4e74b057d0efa0c8398ebcb871
            seek_keys:
              fasta: 7319f9237651755047bc40d7f7a9770d42a537e840f4e105.fa
              fai: 7319f9237651755047bc40d7f7a9770d42a537e840f4e105.fa.fai
              chrom_sizes: 7319f9237651755047bc40d7f7a9770d42a537e840f4e105.chrom.sizes
              dir: .
            asset_parents: []
            asset_children: 
             - 7319f9237651755047bc40d7f7a9770d42a537e840f4e105/bwa_index:default
             - 7319f9237651755047bc40d7f7a9770d42a537e840f4e105/hisat2_index:default
        default_tag: default
      bwa_index:
        asset_description: Genome index for Burrows-Wheeler Alignment Tool, produced with bwa index
        tags:
          default:
            asset_path: bwa_index
            asset_digest: 58073f1e9e77cb2c3b57dc3d26e22e37
            seek_keys:
              bwa_index: 7319f9237651755047bc40d7f7a9770d42a537e840f4e105.fa
              dir: .
            asset_parents: 
             - 7319f9237651755047bc40d7f7a9770d42a537e840f4e105/fasta:default
        default_tag: default
      hisat2_index:
        asset_description: Genome index for HISAT2, produced with hisat2-build
        tags:
          default:
            asset_path: hisat2_index
            asset_digest: 9900974715745390a2ae1efd3cd1c383
            seek_keys:
              hisat2_index: 7319f9237651755047bc40d7f7a9770d42a537e840f4e105
              dir: .
            asset_parents: 
             - 7319f9237651755047bc40d7f7a9770d42a537e840f4e105/fasta:default
        default_tag: default
    aliases: 
     - human_repeats
    genome_description: test description human repeats
  43f14ba8beed34d52edb244e26f193df6edbb467bd55d37a:
    assets:
      fasta:
        asset_description: DNA sequences in the FASTA format, indexed FASTA (produced with samtools index) and chromosome sizes file
        tags:
          default:
            asset_path: fasta
            asset_digest: 8dfe402f7d29d5b036dd8937119e4404
            seek_keys:
              fasta: 43f14ba8beed34d52edb244e26f193df6edbb467bd55d37a.fa
              fai: 43f14ba8beed34d52edb244e26f193df6edbb467bd55d37a.fa.fai
              chrom_sizes: 43f14ba8beed34d52edb244e26f193df6edbb467bd55d37a.chrom.sizes
              dir: .
            asset_parents: []
            asset_children: 
             - 43f14ba8beed34d52edb244e26f193df6edbb467bd55d37a/bwa_index:default
             - 43f14ba8beed34d52edb244e26f193df6edbb467bd55d37a/bowtie2_index:default
        default_tag: default
      bwa_index:
        asset_description: Genome index for Burrows-Wheeler Alignment Tool, produced with bwa index
        tags:
          default:
            asset_path: bwa_index
            asset_digest: 914dec83dcfab73e056717d33ecfd465
            seek_keys:
              bwa_index: 43f14ba8beed34d52edb244e26f193df6edbb467bd55d37a.fa
              dir: .
            asset_parents: 
             - 43f14ba8beed34d52edb244e26f193df6edbb467bd55d37a/fasta:default
        default_tag: default
      bowtie2_index:
        asset_description: Genome index for bowtie, produced with bowtie-build
        tags:
          default:
            asset_path: bowtie2_index
            asset_digest: 738d82a0ff63864726c442b2276d06c0
            seek_keys:
              bowtie2_index: 43f14ba8beed34d52edb244e26f193df6edbb467bd55d37a
              dir: .
            asset_parents: 
             - 43f14ba8beed34d52edb244e26f193df6edbb467bd55d37a/fasta:default
        default_tag: default
    aliases: 
     - mouse_chrM2x
    genome_description: test description mouse chrM2x
  2230c535660fb4774114bfa966a62f823fdb6d21acf138d4:
    assets:
      fasta:
        asset_description: DNA sequences in the FASTA format, indexed FASTA (produced with samtools index) and chromosome sizes file
        tags:
          default:
            asset_path: fasta
            asset_digest: 59fed5ec3c3a95bc5709b24b8f2cf7bf
            seek_keys:
              fasta: 2230c535660fb4774114bfa966a62f823fdb6d21acf138d4.fa
              fai: 2230c535660fb4774114bfa966a62f823fdb6d21acf138d4.fa.fai
              chrom_sizes: 2230c535660fb4774114bfa966a62f823fdb6d21acf138d4.chrom.sizes
              dir: .
            asset_parents: []
        default_tag: default
    aliases: 
     - hg38
    genome_description: test description hg38
genome_archive_folder: /project/shefflab//deploy/rg.databio.org/genomes/archive
genome_archive_config: refgenie_config_archive.yaml
